set clipboard+=unnamedplus
set noswapfile
set undofile
set undodir=$HOME/.config/nvim/undo
set undolevels=10000
set undoreload=10000
set number
set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
